# Generated by Django 4.2.4 on 2023-11-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargaFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=20)),
                ('parentezco', models.CharField(choices=[('PADRE/MADRE', 'Padre o madre'), ('HIJO/HIJA', 'Hijo o hija'), ('CONYUGE', 'Pareja'), ('NO-APLICA', 'No aplica')], default='NO-APLICA', max_length=20)),
                ('direccion', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('NO-ESPECIFICADO', 'No-especificado')], default='NO-ESPECIFICADO', max_length=20)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('correo', models.EmailField(max_length=70, unique=True)),
                ('fecha_nacimiento', models.DateField(max_length=50, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, unique=True)),
                ('jefRRHH', models.BooleanField(default=True)),
                ('trabRRHH', models.BooleanField(default=False)),
                ('trabajador', models.BooleanField(default=False)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('area_desempeno', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=15)),
                ('cargaFamiliar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cargafamiliar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
